### ISSUE TITLE
Assignment_5 

### ISSUE THREAD

**Issue by alopp18** [alopp18/Assignment-5#1]
Here we were provided a dataset with information about the ages (subsample), and length and mass (all fish) for male and female Siscowet Lake Trout captured at four locations in Michigan waters of Lake Superior.

We were tasked with generating two figures:

1. An exploratory plot (sweet and simple)
2. An expository plot (with greater detail and additional visualization tools)   

Data and figures (code and PDF's) can be found within the repo in the labeled folders.

**Comment by mdscheuerell** [comment]
Nice job, Andy! Two things to consider in the future (but the figure is otherwise well done):

1) the yellow points on the white background can be hard for some to see;

2) removing the `NA` label from the legend
